/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book.my.movie.ticket;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;

/**



/**
 *
 * @author SMPS
 */
public class ADDMOVIE extends javax.swing.JFrame {
    ResultSet rs=null;
Connection cn=null;
Statement st=null;
  java.util.Date dt1,dt2;
    /**
     * Creates new form ADDMOVIE
     */
    public ADDMOVIE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addtf = new javax.swing.JTextField();
        add2 = new javax.swing.JButton();
        fd = new com.toedter.calendar.JDateChooser();
        td = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(517, 31, 34, 31);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ADD MOVIE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 278, 47);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("MOVIE NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 200, 32);

        jLabel3.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("FROM DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 170, 32);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("TO DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 190, 124, 32);

        addtf.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        addtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtfActionPerformed(evt);
            }
        });
        getContentPane().add(addtf);
        addtf.setBounds(280, 90, 256, 30);

        add2.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        add2.setForeground(new java.awt.Color(255, 102, 102));
        add2.setText("SUBMIT");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        getContentPane().add(add2);
        add2.setBounds(220, 250, 119, 33);
        getContentPane().add(fd);
        fd.setBounds(280, 140, 260, 30);
        getContentPane().add(td);
        td.setBounds(280, 190, 260, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\Commando_3_(2019)_Hindi_Movie.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 200, 300);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\Drive_(2019)_Hindi_Movie.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 0, 200, 300);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\Hotel_Mumbai_(2019)_Hindi_Movie.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 0, 200, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        try{
            Class.forName("java.sql.Driver");
  cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
 st=cn.createStatement();
    SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd"); 
String s=addtf.getText();
     
 dt1=td.getDate();
        dt2=fd.getDate();
         String tod=(String) sdf.format(td.getDate());
        String frd=(String) sdf.format(fd.getDate());
         Statement st7=cn.createStatement();
          String q7="create table "+s+"(mdate Date,mtime varchar(20) default 0,s1 integer(20) default 0,s2 integer(20) default 0,s3 integer(20) default 0,s4 integer(20) default 0,g1 integer(20) default 0,g2 integer(20) default 0,g3 integer(20) default 0,g4 integer(20) default 0,p1 integer(20) default 0,p2 integer(20) default 0,p3 integer(20) default 0,p4 integer(20) default 0);";
st7.executeUpdate(q7);
String k="Insert into m3 values('"+s+"','"+tod+"','"+frd+"');";
  int i= st.executeUpdate(k);
          if(i==1)
  {  
    
      JOptionPane.showMessageDialog(null,"Submit");
     
  }
  else
     JOptionPane.showMessageDialog(null,"Invalid");
     

    
          
          
          
          
          
          
          
          
        }        catch(Exception a)
        {
        
            System.out.println(a);
        
        }
            
        
    }//GEN-LAST:event_add2ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void addtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDMOVIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDMOVIE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add2;
    private javax.swing.JTextField addtf;
    private com.toedter.calendar.JDateChooser fd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser td;
    // End of variables declaration//GEN-END:variables
}
