/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book.my.movie.ticket;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author SMPS
 */
public class BOOK1 extends javax.swing.JFrame {
    ResultSet rs=null;
Connection cn=null;
Statement st=null;


    /**
     * Creates new form BOOK1
     */
String mdate,mtime="",s="";
int amt=0;
    public BOOK1(String i,String j,String k) {
       mdate=i;
       mtime=j;
       s=k;
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s10 = new javax.swing.JRadioButton();
        s20 = new javax.swing.JRadioButton();
        s30 = new javax.swing.JRadioButton();
        s40 = new javax.swing.JRadioButton();
        g10 = new javax.swing.JRadioButton();
        g20 = new javax.swing.JRadioButton();
        g30 = new javax.swing.JRadioButton();
        g40 = new javax.swing.JRadioButton();
        p10 = new javax.swing.JRadioButton();
        p20 = new javax.swing.JRadioButton();
        p30 = new javax.swing.JRadioButton();
        p40 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("BOOK MY MOVIE TICKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 390, -1));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("SILVER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("GOLD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("PLATINUM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        s10.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        s10.setForeground(new java.awt.Color(0, 255, 204));
        s10.setText("S1");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        getContentPane().add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        s20.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        s20.setForeground(new java.awt.Color(0, 255, 204));
        s20.setText("S2");
        s20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20ActionPerformed(evt);
            }
        });
        getContentPane().add(s20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        s30.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        s30.setForeground(new java.awt.Color(0, 255, 204));
        s30.setText("S3");
        s30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s30ActionPerformed(evt);
            }
        });
        getContentPane().add(s30, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 68, -1, -1));

        s40.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        s40.setForeground(new java.awt.Color(0, 255, 204));
        s40.setText("S4");
        s40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s40ActionPerformed(evt);
            }
        });
        getContentPane().add(s40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        g10.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        g10.setForeground(new java.awt.Color(0, 255, 204));
        g10.setText("G1");
        g10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g10ActionPerformed(evt);
            }
        });
        getContentPane().add(g10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        g20.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        g20.setForeground(new java.awt.Color(0, 255, 204));
        g20.setText("G2");
        g20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g20ActionPerformed(evt);
            }
        });
        getContentPane().add(g20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        g30.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        g30.setForeground(new java.awt.Color(0, 255, 204));
        g30.setText("G3");
        g30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g30ActionPerformed(evt);
            }
        });
        getContentPane().add(g30, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 108, -1, -1));

        g40.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        g40.setForeground(new java.awt.Color(0, 255, 204));
        g40.setText("G4");
        g40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g40ActionPerformed(evt);
            }
        });
        getContentPane().add(g40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        p10.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        p10.setForeground(new java.awt.Color(0, 255, 204));
        p10.setText("P1");
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        p20.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        p20.setForeground(new java.awt.Color(0, 255, 204));
        p20.setText("P2");
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20ActionPerformed(evt);
            }
        });
        getContentPane().add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        p30.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        p30.setForeground(new java.awt.Color(0, 255, 204));
        p30.setText("P3");
        p30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p30ActionPerformed(evt);
            }
        });
        getContentPane().add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 149, -1, -1));

        p40.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        p40.setForeground(new java.awt.Color(0, 255, 204));
        p40.setText("P4");
        p40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p40ActionPerformed(evt);
            }
        });
        getContentPane().add(p40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        b6.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 255, 204));
        b6.setText("BACK");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 255, -1, -1));

        b7.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 255, 204));
        b7.setText("NEXT");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 255, -1, -1));

        jLabel5.setFont(new java.awt.Font("Snap ITC", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("SELECTED");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tf.setColumns(20);
        tf.setFont(new java.awt.Font("Snap ITC", 2, 14)); // NOI18N
        tf.setForeground(new java.awt.Color(0, 255, 204));
        tf.setRows(5);
        jScrollPane1.setViewportView(tf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 368, 22));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\Pagalpanti_(2019)_Hindi_Movie.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\S_P_Chauhan_(2018)_Hindi_Movie.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\SMPS\\Desktop\\book my movie ticket\\images\\Pal_Pal_Dil_Ke_Paas_(2019)_Hindi_Movie.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void g20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g20ActionPerformed
       
        if(g20.isSelected() && g20.isEnabled())
            amt=amt+600;  
          if (g20.isSelected())
     {
        tf.append("G2"); 
         
     }
    }//GEN-LAST:event_g20ActionPerformed

    private void g40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g40ActionPerformed

        if(g40.isSelected() && g40.isEnabled())
            amt=amt+200;       
            if (g40.isSelected())
     {
        tf.append("G4"); 
         
     }
    }//GEN-LAST:event_g40ActionPerformed

    private void g10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g10ActionPerformed
       
        if(g10.isSelected() && g10.isEnabled())
            amt=amt+600;  
            if (g10.isSelected())
     {
        tf.append("G1"); 
         
     }
      
    }//GEN-LAST:event_g10ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
       String s="";
        SelectMovie b=new SelectMovie();
       b.setVisible(true);
     
    }//GEN-LAST:event_b6ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
     if(s10.isSelected() && s10.isEnabled())
            amt=amt+300;  
     if (s10.isSelected())
     {
        tf.append("S1 "); 
         
     }
        
    }//GEN-LAST:event_s10ActionPerformed

    private void s20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20ActionPerformed
        // TODO add your handling code here:
        if(s20.isSelected() && s20.isEnabled())
            amt=amt+300;  
        if (s20.isSelected())
     {
        tf.append("S2 "); 
         
     }
        
    }//GEN-LAST:event_s20ActionPerformed

    private void s30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s30ActionPerformed
        // TODO add your handling code here:
        if(s30.isSelected() && s30.isEnabled())
            amt=amt+300;  
        if (s30.isSelected())
     {
        tf.append("S3 "); 
         
     }
        
    }//GEN-LAST:event_s30ActionPerformed

    private void s40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s40ActionPerformed
        // TODO add your handling code here:
        if(s40.isSelected() && s40.isEnabled())
            amt=amt+300;  
        if (s40.isSelected())
     {
        tf.append("S4 "); 
         
     }
        
    }//GEN-LAST:event_s40ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        try{
         Class.forName("java.sql.Driver");
         int s1=0,s2=0,s3=0,s4=0,p1=0,p2=0,p3=0,p4=0,g1=0,g2=0,g3=0,g4=0;
        Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st1 = cn1.createStatement();
          System.out.println(""+mdate);
            System.out.println(""+mtime);
         if(s10.isSelected())
         {
             s1=1;
            st1.executeUpdate("update "+s+" set s1=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
         }
           
          Connection cn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st2 = cn2.createStatement();
          if(s20.isSelected())
          {
              s2=1;
           st2.executeUpdate("update "+s+" set s2=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          
          }
           Connection cn3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st3 = cn3.createStatement();
          if(s30.isSelected())
          { 
              s3=1;
           st3.executeUpdate("update "+s+" set s3=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          }
           Connection cn4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st4 = cn4.createStatement();
           if(s40.isSelected())
           {
               s4=1;
            st4.executeUpdate("update "+s+" set s4=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
           }
            Connection cn5 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st5 = cn5.createStatement();
           if(g10.isSelected())
           {
               g1=1;
            st5.executeUpdate("update "+s+" set g1=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
           }
            Connection cn6 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st6 = cn6.createStatement();
          if(g20.isSelected())
          {
              g2=1;
           st6.executeUpdate("update "+s+" set g2=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          }
           Connection cn7 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st7 = cn7.createStatement();
          if(g30.isSelected())
          {
              g3=1;
           st7.executeUpdate("update "+s+" set g3=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          }
           Connection cn8 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st8 = cn8.createStatement();
           if(g40.isSelected())
           {
               g4=1;
            st8.executeUpdate("update "+s+" set g4=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
           }
            Connection cn9 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st9 = cn9.createStatement();
          if(p10.isSelected())
          {
              p1=1;
           st9.executeUpdate("update "+s+" set p1=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          }
           Connection cn10 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st10 = cn10.createStatement();
          if(p20.isSelected())
          {
              p2=1;
           st10.executeUpdate("update "+s+" set p2=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
           }
           Connection cn11 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st11 = cn11.createStatement();
          if(p30.isSelected())
          {
              p3=1;
           st11.executeUpdate("update "+s+" set p3=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
          }
           Connection cn12 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st12 = cn12.createStatement();
           if(p40.isSelected())
           {
               p4=1;
            st12.executeUpdate("update "+s+" set p4=1 where mdate='"+mdate+"' && mtime='"+mtime+"';");
           } 
          
          BILL bl=new BILL(s,mtime,mdate,tf.getText(),amt);
         bl.setVisible(true);
         this.setVisible(false);
         
        }
         catch(Exception e){
                 JOptionPane.showMessageDialog(null,"submit");
                         }
                                                  
                                      
        
    }//GEN-LAST:event_b7ActionPerformed

    private void g30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g30ActionPerformed
        // TODO add your handling code here:
        if(g30.isSelected() && g30.isEnabled())
            amt=amt+600;  
            if (g30.isSelected())
     {
        tf.append("G3"); 
         
     }
    }//GEN-LAST:event_g30ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
        if(p10.isSelected() && p10.isEnabled())
            amt=amt+800;  
            if (p10.isSelected())
     {
        tf.append("P1"); 
         
     }
    }//GEN-LAST:event_p10ActionPerformed

    private void p20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20ActionPerformed
        // TODO add your handling code here:
        if(p20.isSelected() && p20.isEnabled())
            amt=amt+800;  
          if (p20.isSelected())
     {
        tf.append("P2"); 
         
     }
    }//GEN-LAST:event_p20ActionPerformed

    private void p30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p30ActionPerformed
        // TODO add your handling code here:
        if(p30.isSelected() && p30.isEnabled())
            amt=amt+800;  
          if (p30.isSelected())
     {
        tf.append("P3"); 
         
     }
    }//GEN-LAST:event_p30ActionPerformed

    private void p40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p40ActionPerformed
        // TODO add your handling code here:
        if(p40.isSelected() && p40.isEnabled())
            amt=amt+100;
        if (p40.isSelected())
     {
        tf.append("P4"); 
         
     }
    }//GEN-LAST:event_p40ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       try{
         Class.forName("java.sql.Driver");
         int s1=0,s2=0,s3=0,s4=0,p1=0,p2=0,p3=0,p4=0,g1=0,g2=0,g3=0,g4=0;
        Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_movie_ticket","root","1234");
         Statement st1 = cn1.createStatement();
       
        rs=st1.executeQuery("select * from "+s+" where mdate='"+mdate+"' && mtime='"+mtime+"';");
       if(rs.next())
       { System.out.print("dsdf");
        s1=rs.getInt("s1");
        s2=rs.getInt("s2"); 
        s3=rs.getInt("s3");
        s4=rs.getInt("s4");
        g1=rs.getInt("g1");
        g2=rs.getInt("g2"); 
        g3=rs.getInt("g3");
        g4=rs.getInt("g4");
        p1=rs.getInt("p1");
        p2=rs.getInt("p2"); 
        p3=rs.getInt("p3");
        p4=rs.getInt("p4");
       
       }
       if(s1==1)
       {
           s10.setSelected(true);
           s10.setEnabled(false);
       }
         if(s2==1)
       {
           s20.setSelected(true);
           s20.setEnabled(false);
       }
         if(s3==1)
       {
           s30.setSelected(true);
           s30.setEnabled(false);
       }
           if(s4==1)
       {
           s40.setSelected(true);
           s40.setEnabled(false);
       }
            if(g1==1)
       {
           g10.setSelected(true);
           g10.setEnabled(false);
       }
         if(g2==1)
       {
           g20.setSelected(true);
           g20.setEnabled(false);
       }
         if(g3==1)
       {
           g30.setSelected(true);
           g30.setEnabled(false);
       }
           if(s4==1)
       {
           g40.setSelected(true);
           g40.setEnabled(false);
       }
            if(p1==1)
       {
           p10.setSelected(true);
           p10.setEnabled(false);
       }
         if(p2==1)
       {
           p20.setSelected(true);
           p20.setEnabled(false);
       }
         if(p3==1)
       {
           p30.setSelected(true);
           p30.setEnabled(false);
       }
           if(p4==1)
       {
          p40.setSelected(true);
          p40.setEnabled(false);
       }
  }
       catch(Exception e){
                 JOptionPane.showMessageDialog(null,"submit");
                 
                 }
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BOOK1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JRadioButton g10;
    private javax.swing.JRadioButton g20;
    private javax.swing.JRadioButton g30;
    private javax.swing.JRadioButton g40;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton p10;
    private javax.swing.JRadioButton p20;
    private javax.swing.JRadioButton p30;
    private javax.swing.JRadioButton p40;
    private javax.swing.JRadioButton s10;
    private javax.swing.JRadioButton s20;
    private javax.swing.JRadioButton s30;
    private javax.swing.JRadioButton s40;
    private javax.swing.JTextArea tf;
    // End of variables declaration//GEN-END:variables
}
