
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMPS
 */
public class vote extends javax.swing.JFrame {
Connection con =null;
Statement st =null;
ResultSet rs =null;
ResultSet rs1 =null;
Statement st1 =null;
Statement st2 =null;
    /**
     * Creates new form vote
     */
    String uid="";

    public vote(String s) {
   uid=s;
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbA = new javax.swing.JRadioButton();
        rbJ = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        logout = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("vote");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(96, 0, 107, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Party");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 58, 40, 22);

        jLabel3.setText("BJP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 143, 17, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chrysanthemum.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 87, 40, 50);

        jLabel5.setText("CONG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 221, 29, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jellyfish.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 163, 29, 47);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lighthouse.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 241, 40, 55);

        jLabel8.setText("MGH");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 304, 22, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel9.setText("CANDIDATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(137, 52, 126, 29);

        jLabel10.setText("Akshat");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(152, 101, 33, 14);

        jLabel11.setText("Mahesh");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(137, 184, 37, 14);

        jLabel12.setText("Anurag");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(137, 241, 35, 14);

        rbA.setText("vote");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });
        getContentPane().add(rbA);
        rbA.setBounds(332, 97, 47, 23);

        rbJ.setText("vote");
        rbJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJActionPerformed(evt);
            }
        });
        getContentPane().add(rbJ);
        rbJ.setBounds(332, 175, 47, 23);

        rbM.setText("vote");
        rbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMActionPerformed(evt);
            }
        });
        getContentPane().add(rbM);
        rbM.setBounds(340, 254, 47, 23);

        jToggleButton1.setText("vote");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(120, 320, 55, 23);

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(190, 320, 63, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Koala.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-10, 10, 480, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
     if(rbA.isSelected())
     {
         rbJ.setSelected(false);
        rbM.setSelected(false);
     }
    
    }//GEN-LAST:event_rbAActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      String b="";
        if(rbA.isSelected())
       {
           b ="Akshat";
       }
       else if (rbJ.isSelected())
           {
               b ="Mahesh";
           }
           else if (rbM.isSelected())
                   {
                   b ="Anurag";
                   }
           else
               System.out.print("No such record found");
        try{
         Class.forName("java.sql.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","1234");
         st = con.createStatement();
           st1 = con.createStatement();
           st2 = con.createStatement();
         String query= "SELECT *FROM party WHERE Candidate ='"+ b+ "';" ;
          String J ="UPDATE vote SET vote = 1 WHERE votername ='" + uid+ "';";
    rs = st.executeQuery(query);
     int i=0; int n=0;
  if(rs.next())
  {
   int k= st1.executeUpdate(J);
      
   i=rs.getInt("vote");
 n = i +1;
  
  }
  
  String M= "UPDATE party SET vote = "+n+" WHERE Candidate ='"+ b+ "';" ;
   int o= st2.executeUpdate(M);
   if(o==1)
         JOptionPane.showMessageDialog(null,"succesfully updates");
else
        JOptionPane.showMessageDialog(null,"not chnage"); 
  
    
      
        }
         catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Error in connectivity");
                         }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void rbJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJActionPerformed
        if(rbA.isSelected())
     {
         rbJ.setSelected(false);
        rbM.setSelected(false);
     }
    }//GEN-LAST:event_rbJActionPerformed

    private void rbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMActionPerformed
        if(rbM.isSelected())
     {
         rbJ.setSelected(false);
        rbA.setSelected(false);
     }
    }//GEN-LAST:event_rbMActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
      if(rbA.isSelected())
      {
          logout.setEnabled(true);
          loginadmin lo =new loginadmin();
          lo.setVisible(true);
      }
      else if(rbM.isSelected())
      {
          logout.setEnabled(true);
            loginadmin lo =new loginadmin();
          lo.setVisible(true);
          
      }
       else if(rbJ.isSelected())
      {
          logout.setEnabled(true);
           loginadmin lo =new loginadmin();
          lo.setVisible(true);
          
      }
       else 
           JOptionPane.showMessageDialog(null,"please votefirst");
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new vote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbJ;
    private javax.swing.JRadioButton rbM;
    // End of variables declaration//GEN-END:variables
}
